"""initial_azure_schema

Revision ID: 007960098000
Revises: 
Create Date: 2026-05-01 18:26:58.365807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007960098000'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_watchlists_user_id'), 'watchlists', ['user_id'], unique=False, schema='app')
    op.create_index('unique_user_watchlist_name', 'watchlists', ['user_id', sa.literal_column('lower(name)')], unique=True, schema='app')
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['app.watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_instrument'),
    schema='app'
    )
    op.create_index(op.f('ix_app_watchlist_items_instrument_id'), 'watchlist_items', ['instrument_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_watchlist_items_watchlist_id'), table_name='watchlist_items', schema='app')
    op.drop_index(op.f('ix_app_watchlist_items_instrument_id'), table_name='watchlist_items', schema='app')
    op.drop_table('watchlist_items', schema='app')
    op.drop_index('unique_user_watchlist_name', table_name='watchlists', schema='app')
    op.drop_index(op.f('ix_app_watchlists_user_id'), table_name='watchlists', schema='app')
    op.drop_table('watchlists', schema='app')
    # ### end Alembic commands ###
