CREATE TABLE Finance_bs (
    -- Composite Primary Key
    Fincode                 INT NOT NULL,
    Year_end                INT NOT NULL,
    Type                    VARCHAR(1) NOT NULL, -- S = Standalone
    
    -- Basic Info
    No_months               INT,
    Unit                    VARCHAR(50),
    
    -- Equity and Liabilities
    Share_Capital           FLOAT,
    Shares_warrants         FLOAT,
    Shares_application_money FLOAT,
    ESOP_Outstanding        FLOAT,
    Share_suspense          FLOAT,
    Reserve                 FLOAT,
    Sharehoders_funds       FLOAT,
    Deposits                FLOAT,
    Borrowings              FLOAT,
    Other_liabilities       FLOAT,
    Total_sounces_Funds     FLOAT,
    
    -- Assets
    Cash_balances_RBI       FLOAT,
    Bank_Call_money         FLOAT,
    Investments             FLOAT,
    Advances                FLOAT,
    Gross_block             FLOAT,
    Acc_Depreciation        FLOAT,
    Impairment_assets       FLOAT,
    Lease_adj               FLOAT,
    CWIP                    FLOAT,
    Other_Assets            FLOAT,
    Total_Applications      FLOAT,
    Contingent_liabilities  FLOAT,
    Bills_For_Collection    FLOAT,
    Ltrm_Borrowing          FLOAT,
    Secured_Loans           FLOAT,
    Unsecured_Loans_Nf      FLOAT,
    Net_Def_Tax_Nf          FLOAT,
    Oth_Lt_Liab             FLOAT,
    Lt_Trade_Payables       FLOAT,
    Lt_Provisions           FLOAT,
    Total_Nonliab           FLOAT,
    Trade_Payables          FLOAT,
    Current_Liabilities_Nf  FLOAT,
    St_Borrowings           FLOAT,
    Provisions              FLOAT,
    Current_Laib_Prov_Nf    FLOAT,
    Total_Sounces_Funds_Nf  FLOAT,
    
    -- Fixed: SR NO 45 and 52 were duplicates. 52 is now Lt_Loanadv
    Non_Current_Assets      FLOAT, 
    Loan_Non_Cuurent_Assets FLOAT, 
    Net_Block               FLOAT,
    Cwip_Nf                 FLOAT,
    Intang_Assetunderdev    FLOAT,
    Pre_Operatieve_Exps     FLOAT,
    Assetsintransit         FLOAT,
    Investments_Nf          FLOAT, 
    Lt_Loanadv              FLOAT, -- Corrected from duplicate name
    Other_Noc_Assets        FLOAT,
    Total_Nonassets         FLOAT,
    Current_Investments     FLOAT,
    Inventory               FLOAT,
    Debtors                 FLOAT,
    Cash_Bank               FLOAT,
    Other_Current_Nf        FLOAT,
    Loans_Adv               FLOAT,
    Currant_Assets_Nf       FLOAT,
    Net_Current_Assets_Nf   FLOAT,
    Other_Crnt_Assets       FLOAT,
    Misc_Exps_Not_Wo        FLOAT,
    Total_Applications_Nf   FLOAT,
    
    -- Financials Continued
    Total_Debt              FLOAT,
    Total_Debt_Inclst_Nf    FLOAT,
    Book_Nav_Share          FLOAT,
    Adj_Bv                  FLOAT,
    Minority_Interest       FLOAT,
    Equity_Authorised       FLOAT,
    Equity_Issued           FLOAT,
    EQUITY_PAIDUP           FLOAT,
    Equity_Forfeited        FLOAT,
    Adj_Equity              FLOAT,
    Preference_Capital      FLOAT,
    FACE_VALUE              FLOAT,
    Share_Premium           FLOAT,
    Capital_Reserve         FLOAT,
    Profit_Loss             FLOAT,
    General_Reserve         FLOAT,
    Reserve_Excl_Revaluation FLOAT,
    Revaluation_Reserve     FLOAT,
    Demand_Deposits         FLOAT,
    Saving_Deposits         FLOAT,
    Term_Fixed_Deposits     FLOAT,
    Current_Deposits        FLOAT,
    Recurring_Deposits      FLOAT,
    Borrowings_RBI          FLOAT,
    Borrowings_Banks        FLOAT,
    Borrowings_GOI          FLOAT,
    Borrowings_FI           FLOAT,
    Borrowings_Bonds        FLOAT,
    Borrowings_Other        FLOAT,
    Borrowings_Outof_India  FLOAT,
    Bills_payable           FLOAT,
    Inter_oofice_adjustments_liabilities FLOAT,
    Interest_accrued        FLOAT,
    Proposed_dividend       FLOAT,
    Corporate_dividend_tax  FLOAT,
    Cash_RBI                FLOAT,
    Cash_In_hand            FLOAT,
    Investments_India       FLOAT,
    GOI_Securities          FLOAT,
    Equity_Shares_corporate FLOAT,
    Debentures_Bonds        FLOAT,
    Subsidiaries_Joint_ventures FLOAT,
    Mutual_Funds_insurance_Units FLOAT,
    Investments_Outside_India FLOAT,
    GOI_Securities_Outside_india FLOAT,
    Subsidiaries_Joint_ventures_outside_india FLOAT,
    Other_investments_outside_India FLOAT,
    Dimunition_Investments  FLOAT,
    Bills_purchased_discounted FLOAT,
    Cash_credit_overdraft   FLOAT,
    Term_Loans              FLOAT,
    Finance_Lease_Hire_purchase FLOAT,
    Buildings               FLOAT,
    Assets_despose          FLOAT,
    Other_fix_assets        FLOAT,
    Inter_office_adjustments_Assets FLOAT,
    Interest_accrued_assets FLOAT,
    Advance_tax_TDS         FLOAT,
    Stationery_stamps       FLOAT,
    Non_banking_assets      FLOAT,
    Deferred_tax_Assets     FLOAT,
    Misc_expenditures_Not_writtoff FLOAT,
    Claims_Not_acknowledge_debt FLOAT,
    Outstanding_Forward_Exchange_Contra FLOAT, -- Corrected name
    Guarantees_Constituents_India FLOAT,
    Guarantees_Constituents_Outside_India FLOAT,
    Acceptances_Endorsements_Obligations FLOAT,
    Non_Convertible_Debenture FLOAT,
    Conv_Debenture_Bnds     FLOAT,
    Packing_Credit          FLOAT,
    Intercorpsecdeposits    FLOAT,
    Term_Loan_Bank          FLOAT,
    Term_Loan_Inst          FLOAT,
    Fixed_Deposits          FLOAT,
    Loans_Susidiaries       FLOAT,
    Inter_Corp_Deposits     FLOAT,
    Foreign_Curr_Convertible_Notes FLOAT,
    Foreign_Curr_Long_Term_Loans FLOAT,
    Loans_Bank              FLOAT,
    Loans_Govt              FLOAT,
    Loans_Others            FLOAT,
    Def_Tax_Assets          FLOAT,
    Def_Tax_Liability       FLOAT,
    Sundry_Crs              FLOAT,
    Acceptances             FLOAT,
    Trade_Paysubs           FLOAT,
    Bank_Od                 FLOAT,
    Adv_Customers           FLOAT,
    Interest_Not_Due        FLOAT,
    Share_Application       FLOAT,
    Cl_Curmat_Deb           FLOAT,
    Cl_Curmat_Others        FLOAT,
    Loans                   FLOAT,
    Stbs_Sec_Loandemand     FLOAT,
    Stbs_Wcap               FLOAT,
    Stbu_Buycredit          FLOAT,
    Stbu_Commborr           FLOAT,
    Proposed_Divided        FLOAT,
    Prov_Corp_Tax           FLOAT,
    Prov_Tax                FLOAT,
    Prov_Retirements        FLOAT,
    Prefence_Dividend       FLOAT,
    Long_Term_Investments_Nf FLOAT,
    Long_Term_Quoted        FLOAT,
    Long_Term_Unquoted      FLOAT,
    CURRENT_QUOTED          FLOAT,
    Raw_Material            FLOAT,
    Wip                     FLOAT,
    Fin_Goods               FLOAT,
    Packing_Materials_Inventory FLOAT,
    Store_Spares            FLOAT,
    Drs_Six_Months          FLOAT,
    Drs_Others              FLOAT,
    Cash_Hand               FLOAT,
    Bank_Balance            FLOAT,
    Interest_Investments    FLOAT,
    Interest_Debentures     FLOAT,
    Deposits_Govt_Other     FLOAT,
    Interest_Accrued_Due    FLOAT,
    Prepaid_Exps            FLOAT,
    Adv_Cash_Kind           FLOAT,
    Adv_Tax                 FLOAT,
    Due_Director            FLOAT,
    Due_Subsidiaries        FLOAT,
    Inter_Corporate_Deposits FLOAT,
    Corporate_Deposits      FLOAT,
    flag                    VARCHAR(1),
    
    PRIMARY KEY (Fincode, Year_end, Type),
    FOREIGN KEY (Fincode) REFERENCES Company_Master(FINCODE)
);